<?php

namespace tests\Unit\App\Services;

use app\Services\CsvPortfolioItemsConverter;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class PortfolioItemsConverterTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_convert_excel_file_to_portfolio_items()
    {
        // Given
        $portfolioItems = array(
            array("Title", "Titel", "Main Image URL", "Description", "Beschrijving", "Website URL", "Image 1 URL", "Image 2 URL", "Image 3 URL", "Image 4 URL", "Image 5 URL", "Image 6 URL", "Image 7 URL", "Tag 1", "Tag 2", "Tag 3", "Tag 4", "Bullet 1 NL", "Bullet 1 NL", "Bullet 2 NL", "Bullet 2 NL", "Bullet 3 NL", "Bullet 3 EN"),
            array("Test Title 1", "Test Titel 1", "main-image-url-1", 'Description 1', "Beschrijving 1", 'website-url-1', "image-1-url", "image-2-url", "image-3-url", "image-4-url", "image-5-url", "image-6-url", "image-7-url", "Tag 1", "Tag 2", "Tag 3", "Tag 4", "Bullet 1", "Bullet 2", "Bullet 3", "Bullet 4", "Bullet 5", "Bullet 6")
        );

        $filename = 'portfolio_items.csv';
        $path = storage_path()."/imports/".$filename;

        $file = fopen($path, 'w');
        foreach ($portfolioItems as $portfolioItem)
        {
            fputcsv($file, $portfolioItem);
        }

        fclose($file);

        $file =  new UploadedFile( $path, $filename, null,null,true);

        // When
        $portfolioItems = CsvPortfolioItemsConverter::toEntity($file);

        // Then
        self::assertEquals(1, sizeof($portfolioItems));

    }

    /** @test */
    public function it_should_have_no_images(){

        // Given
        $portfolioItems = array(
            array("Title", "Titel", "Main Image URL", "Description", "Beschrijving", "Website URL", "Image 1 URL", "Image 2 URL", "Image 3 URL", "Image 4 URL", "Image 5 URL", "Image 6 URL", "Image 7 URL", "Tag 1", "Tag 2", "Tag 3", "Tag 4", "Bullet 1 NL", "Bullet 1 NL", "Bullet 2 NL", "Bullet 2 NL", "Bullet 3 NL", "Bullet 3 EN"),
            array("Test Title 1", "Test Titel 1", "main-image-url-1", 'Description 1', "Beschrijving 1", 'website-url-1', "", "", "", "", "", "", "", "Tag 1", "Tag 2", "Tag 3", "Tag 4", "Bullet 1", "bullet 2", "Bullet 3", "Bullet 4", "Bullet 5", "Bullet 6")
        );

        $filename = 'portfolio_items.csv';
        $path = storage_path()."/imports/".$filename;

        $file = fopen($path, 'w');
        foreach ($portfolioItems as $portfolioItem)
        {
            fputcsv($file, $portfolioItem);
        }

        fclose($file);

        $file =  new UploadedFile( $path, $filename, null,null,true);

        // When
        $portfolioItems = CsvPortfolioItemsConverter::toEntity($file);

        // Then
        self::assertEmpty($portfolioItems->first()->images());
    }

    /** @test */
    public function it_should_have_no_tags(){

        // Given
        $portfolioItems = array(
            array("Title", "Titel","Main Image URL", "Description", "Beschrijving", "Website URL", "Image 1 URL", "Image 2 URL", "Image 3 URL", "Image 4 URL", "Image 5 URL", "Image 6 URL", "Image 7 URL", "Tag 1", "Tag 2", "Tag 3", "Tag 4", "Bullet 1 NL", "Bullet 1 NL", "Bullet 2 NL", "Bullet 2 NL", "Bullet 3 NL", "Bullet 3 EN"),
            array("Test Title 1", "Test Titel 1", "main-image-url-1", 'Description 1', "Beschrijving 1", 'website-url-1', "image-1-url", "image-2-url", "image-3-url", "image-4-url", "image-5-url", "image-6-url", "image-7-url", "", "", "", "", "Bullet 1", "bullet 2", "Bullet 3", "Bullet 4", "Bullet 5", "Bullet 6")
        );

        $filename = 'portfolio_items.csv';
        $path = storage_path()."/imports/".$filename;

        $file = fopen($path, 'w');
        foreach ($portfolioItems as $portfolioItem)
        {
            fputcsv($file, $portfolioItem);
        }

        fclose($file);

        $file =  new UploadedFile( $path, $filename, null,null,true);

        // When
        $portfolioItems = CsvPortfolioItemsConverter::toEntity($file);

        // Then
        self::assertEmpty($portfolioItems->first()->tags());
    }
}
