<?php

namespace Tests\Feature\PortfolioManagement;

use App\PortfolioManagement\Application\AddPortfolioItems\AddPortfolioItems;
use App\PortfolioManagement\Application\AddPortfolioItems\AddPortfolioItemsInput;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItemFactory;
use Tests\TestCase;
use Tests\Unit\PortfolioManagement\DummyPortfolioItemRepository;

class AddPortfolioItemsTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->portfolioItemRepository = new DummyPortfolioItemRepository();
    }

    /** @test */
    public function it_should_add_portfolio_items()
    {
        // Given
        $portfolioItems = PortfolioItemFactory::create(20);
        $portfolioItemsAsArray = [];

        foreach ($portfolioItems as $portfolioItem)
        {
            $portfolioItemsAsArray[] = $portfolioItem->asArray();
        }

        // When
        $useCase = new AddPortfolioItems($this->portfolioItemRepository);
        $useCaseInput = new AddPortfolioItemsInput([
            "portfolio_items" => $portfolioItemsAsArray
        ]);

        // When
        $useCaseResult = $useCase->execute($useCaseInput);

        // Then
        self::assertEquals($portfolioItems, $this->portfolioItemRepository->all());
    }
}
