<?php

namespace Tests\Feature\PortfolioManagement;

use App\PortfolioManagement\Application\GetAllPortfolioItems\GetAllPortfolioItems;
use App\PortfolioManagement\Application\GetAllPortfolioItems\GetAllPortfolioItemsInput;
use App\PortfolioManagement\Application\GetPortfolioItemsWithTag\GetPortfolioItemsWithTag;
use App\PortfolioManagement\Application\GetPortfolioItemsWithTag\GetPortfolioItemsWithTagInput;
use App\PortfolioManagement\Domain\PortfolioItems\ImageFactory;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItem;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItemFactory;
use App\PortfolioManagement\Domain\Repositories\PortfolioItemRepositoryInterface;
use App\PortfolioManagement\Infrastructure\Persistence\Eloquent\PortfolioItems\Repositories\EloquentPortfolioItemRepository;
use Tests\TestCase;
use Tests\Unit\PortfolioManagement\DummyPortfolioItemRepository;

class GetAllPortfolioItemsTest extends TestCase
{
    private PortfolioItemRepositoryInterface $portfolioItemRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->portfolioItemRepository = new DummyPortfolioItemRepository();
    }

    /** @test */
    public function it_should_return_all_portfolio_items()
    {
        $portfolioItems = PortfolioItemFactory::create(50);
        $this->portfolioItemRepository->addMultiple($portfolioItems);

        $useCase = new GetAllPortfolioItems($this->portfolioItemRepository);
        $useCaseInput = new GetAllPortfolioItemsInput();
        $useCaseResult = $useCase->execute($useCaseInput);

        $resultingPortfolioItems = $useCaseResult->portfolioItems();

        self::assertEquals(sizeof($portfolioItems), sizeof($resultingPortfolioItems));
    }

    /** @test */
    public function it_should_return_portfolio_items_with_certain_tag()
    {
        $images = collect();
        $firstTag = "Tag 1";
        $secondTag = "Tag 2";
        $tags = collect(array($firstTag, $secondTag));

        $portfolioItemWithTags = new PortfolioItem("Title", ImageFactory::placeholder(), "Description", "Website Url", $images, $tags);
        $portfolioItemsWithoutTags = PortfolioItemFactory::create(50);

        $this->portfolioItemRepository->add($portfolioItemWithTags);
        $this->portfolioItemRepository->addMultiple($portfolioItemsWithoutTags);

        $useCase = new GetPortfolioItemsWithTag($this->portfolioItemRepository);
        $useCaseInput = new GetPortfolioItemsWithTagInput([
            "tag" => $firstTag
        ]);

        $useCaseResult = $useCase->execute($useCaseInput);

        self::assertEquals($useCaseResult->portfolioItems()->first(), $portfolioItemWithTags);

    }
}
