<?php

namespace Tests\Feature\PortfolioManagement;

use App\PortfolioManagement\Application\GetPortfolioItemsWithTag\GetPortfolioItemsWithTag;
use App\PortfolioManagement\Application\GetPortfolioItemsWithTag\GetPortfolioItemsWithTagInput;
use App\PortfolioManagement\Domain\PortfolioItems\BulletPointFactory;
use App\PortfolioManagement\Domain\PortfolioItems\Description;
use App\PortfolioManagement\Domain\PortfolioItems\ImageFactory;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItem;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItemFactory;
use App\PortfolioManagement\Domain\PortfolioItems\Title;
use App\PortfolioManagement\Domain\Repositories\PortfolioItemRepositoryInterface;
use Illuminate\Support\Facades\App;
use Tests\TestCase;
use Tests\Unit\PortfolioManagement\DummyPortfolioItemRepository;
use Tests\Unit\PortfolioManagement\ReturnConstantPortfolioItemRepository;

class GetPortfolioItemsWithTagTest extends TestCase
{
    private PortfolioItemRepositoryInterface $portfolioItemRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->portfolioItemRepository = new DummyPortfolioItemRepository();
    }

    /** @test */
    public function it_should_return_portfolio_items_with_certain_tag()
    {
        $images = collect();
        $firstTag = "Tag 1";
        $secondTag = "Tag 2";
        $tags = collect(array($firstTag, $secondTag));
        $bulletPoints = BulletPointFactory::multiple(10);

        $portfolioItemWithTags = new PortfolioItem(new Title("Title", "Titel"), ImageFactory::placeholder(), new Description("Description", "Beschrijving"), "Website Url", 1, $images, $tags, $bulletPoints);
        $portfolioItemsWithoutTags = PortfolioItemFactory::create(50);

        $this->portfolioItemRepository->add($portfolioItemWithTags);
        $this->portfolioItemRepository->addMultiple($portfolioItemsWithoutTags);

        $useCase = new GetPortfolioItemsWithTag($this->portfolioItemRepository);
        $useCaseInput = new GetPortfolioItemsWithTagInput([
            "tag" => $firstTag
        ]);

        $useCaseResult = $useCase->execute($useCaseInput);

        self::assertEquals($useCaseResult->portfolioItems()->first(), $portfolioItemWithTags);

    }

    /** @test */
    public function it_should_return_portfolio_items_with_tag_when_route_is_called()
    {
        $this->withoutExceptionHandling();

        $portfolioItemRepository = new ReturnConstantPortfolioItemRepository();
        $tag = $portfolioItemRepository->all()->first()->tags()->first();
        App::bind(PortfolioItemRepositoryInterface::class, ReturnConstantPortfolioItemRepository::class);

        $response = $this->get(route("all-portfolio-items")."?tag=".$tag);

        $portfolioItems = $response["payload"]['portfolio_items']["data"];

        self::assertNotEmpty($portfolioItems);

        foreach ($portfolioItems as $portfolioItem)
        {
            self::assertNotEmpty($portfolioItem);
        }
    }
}
