<?php

namespace Tests\Unit\CustomerRelationshipManagement;

use App\CustomerRelationshipManagement\Domain\Customers\CustomerFactory;
use Tests\TestCase;

class CustomerFactoryTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_return_a_customer(){

        // Given

        // When
        $customers = CustomerFactory::create();


        // Then
        self::assertEquals(1, sizeof($customers));
    }

    /** @test */
    public function it_should_return_customers_with_selected_attributes(){

        // Given


        // When


        // Then
        self::assertEquals(true, false);
    }
}
