<?php

namespace Tests\Unit\CustomerRelationshipManagement;

use App\CustomerRelationshipManagement\Domain\Customers\Customer;
use App\CustomerRelationshipManagement\Domain\Customers\CustomerFactory;
use Tests\TestCase;

class CustomerFactoryTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_return_one_customer(){

        // Given

        // When
        $customer = CustomerFactory::create();


        // Then
        self::assertInstanceOf(Customer::class, $customer);
    }

    /** @test */
    public function it_should_return_customers_with_selected_attributes(){

        // Given
        $firstName = "John";
        $lastName = "Doe";
        $email = 'johndoe@example.com';

        $attributes = [
            'first_name' => $firstName,
            'last_name' => $lastName,
            'email' => $email
        ];

        // When
        $customer = CustomerFactory::create(1, $attributes);

        // Then
        self::assertEquals($customer->firstName(), $firstName);
        self::assertEquals($customer->lastName(), $lastName);
        self::assertEquals($customer->email(), $email);

    }
}
