<?php

namespace Tests\Unit\CustomerRelationshipManagement;

use App\CustomerRelationshipManagement\Domain\Notifications\Recipient;
use App\Jobs\SendMailJob;
use Illuminate\Mail\Mailable;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

class SendMailJobTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_send_an_email_to_correct_recipient(){

        // Given
        Mail::fake();
        $mailable = new DummyMail();
        $recipientEmailAddress = "john@example.com";
        $job = new SendMailJob($mailable, $recipientEmailAddress);

        // When
        $job->handle();

        // Then
        Mail::assertSent(DummyMail::class, function (Mailable $mail) use ($recipientEmailAddress){
            return $mail->hasTo($recipientEmailAddress);
        });
    }
}
