<?php

use App\Http\Middleware\HandleCorsMiddleware;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

beforeEach(function () {
    // TODO: Change the autogenerated stub
});

it('should set correct headers', function () {
    $request = new Request;
    $middleware = new HandleCorsMiddleware;
    $response = $middleware->handle($request, function (Request $request) {
        return new Response;
    });

    expect($response->headers->get('Access-Control-Allow-Origin'))->not->toBeNull();
});
