<?php

namespace App\PortfolioManagement\Infrastructure\Persistence\Eloquent\PortfolioItems;

/**
 * @property string $title
 * @property string $main_image_url;
 * @property string $description;
 * @property string $website_url
 */
class EloquentPortfolioItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = "portfolio_items";
    protected $fillable = [
        "title", "main_image_url", "description", "website_url"
    ];

    public function tags()
    {
        return $this->belongsToMany(EloquentTag::class, "portfolio_item_tag", "portfolio_item_id", "tag_id");
    }

    public function images()
    {
        return $this->hasMany(EloquentImage::class, 'portfolio_item_id');
    }

    public function save(array $options = [])
    {
        $save = parent::save($options); // TODO: Change the autogenerated stub
        $this->tags()->saveMany($this->tags);
        $this->images()->saveMany($this->images);
        return $save;
    }
}
