<?php

namespace Tests\Unit;

use App\Http\Middleware\HandleCorsMiddleware;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use PHPUnit\Framework\TestCase;

class HandleCorsMiddlewareTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_set_correct_headers()
    {
        $request = new Request();
        $middleware = new HandleCorsMiddleware();
        $response = $middleware->handle($request, function (Request $request) {
            return new Response();
        });

        $this->assertNotNull($response->headers->get('Access-Control-Allow-Origin'));
    }
}
