<?php

namespace Tests\Unit\PortfolioManagement;

use App\PortfolioManagement\Domain\PortfolioItems\Image;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItem;
use Tests\TestCase;

class ImageTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->url = "/images/placeholder.png";
        $this->image = new Image($this->url);
    }

    /** @test */
    public function it_should_return_the_correct_url()
    {
        self::assertEquals($this->url, $this->image->url());
    }
}
