<?php

namespace Tests\Unit\PortfolioManagement;

use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItemFactory;
use App\PortfolioManagement\Domain\Repositories\PortfolioItemRepositoryInterface;
use App\PortfolioManagement\Infrastructure\Services\PortfolioManagementService;
use Tests\TestCase;

class PortfolioManagementServiceTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->portfolioItemRepository = new DummyPortfolioItemRepository();
        $this->portfolioManagementService = new PortfolioManagementService($this->portfolioItemRepository);
    }

    /** @test */
    public function it_should_execute_add_portfolio_items_use_case()
    {
        // Given
        $portfolioItems = PortfolioItemFactory::create(20);

        // When
        $this->portfolioManagementService->addPortfolioItems($portfolioItems);

        // Then
        self::assertEquals($portfolioItems, $this->portfolioItemRepository->all());
    }
}
