<?php

namespace Tests\Unit\PortfolioManagement;

use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItem;
use App\PortfolioManagement\Domain\PortfolioItems\PortfolioItemFactory;
use Tests\TestCase;

class PortfolioItemFactoryTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_should_create_portfolio_items_with_specified_quantity()
    {
        $amount = 100;
        $portfolioItems = PortfolioItemFactory::create($amount);
        self::assertEquals($amount, sizeof($portfolioItems));

        foreach ($portfolioItems as $portfolioItem)
        {
            self::assertInstanceOf(PortfolioItem::class, $portfolioItem);
        }
    }

    /** @test */
    public function it_should_create_portfolio_items_with_specified_tag()
    {
        $tag = "Test Tag";
        $portfolioItems = PortfolioItemFactory::create(10, [
            "tag" => $tag
        ]);

        foreach ($portfolioItems as $portfolioItem)
        {
            self::assertEquals($tag, $portfolioItem->tags()->first());
        }
    }
}
